name: Integration Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests on'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}
    - name: Install Flutter SDK
      run: |
        git clone https://github.com/flutter/flutter.git -b stable
        export PATH="$PATH:  ./flutter/bin"
    - name: Changing Current directory
      run: cd ./flutter
    - name: Grant execute permission on Flutter binary
      run: chmod +x flutter/bin/flutter
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter test CIS350/stock_it_application/test/trial_test.dart
